// AUTO_GENERATED BY Caglar Kurtkaya
package Outputs;

import java.lang.Override;
import java.lang.String;

public class Chase implements Bank {
  @Override
  public String getName() {
    return "Chase";
  }
}
