// AUTO_GENERATED BY Caglar Kurtkaya
package Outputs;

import java.lang.Override;

public class MyFactory implements AbstractFactory {
  @Override
  public Bank createBank() {
    return new Chase();
  }
}
